import time
import os
def clear():
    if os.name == 'nt':
        os.system('cls')
    else:
        os.system('clear')
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print()
print('Friends. Yelling. Light. A portal. \nYou startle awake, wildly swinging at nothing as you stumble backwards into a tree trunk. \nYou\'re covered in mud and your breathing is ragged. You swear there was a portal behind you. \nWhere is it now?')
print('\nYou force your eyes open, taking in your surroundings. A babbling brook. Tiny huts made of straw and twigs. Towering trees. Flowers everywhere. ')
print('Your panic fades as you stare at this storybook forest. It\'s like you\'ve fallen into a fairytale. \nSomething rough brushed against your cheek. \n \nEverything fades to black.')
print()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
time.sleep(25)
clear()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print()
print('"It\'s awake!", a tiny mushroom squeals. You jolt upright. A talking mushroom? \n"Poppy! stop frightening our guest!"')
time.sleep(3)
player_name = input('What is your name? \n>>> ')
print()
print(f'"I\'m Poppy! and this is Master Oakley!" \n"Welcome to Mossy Meadows, {player_name}", says Oakley. "I\'ve never seen you here before."')
time.sleep(5)
print('"I...don\'t know why I\'m here."')
time.sleep(3)
print('Oakley nods. "Rest for now, we can talk later"')
print()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
clear()
time.sleep(5)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print()
print('Later that afternoon, Master Oakley offers to show you the village')
print('The market is small, but lively. Frogs bid on flies. Snails buy new shells. Flowers are everywhere.')
time.sleep(5)
print('"Where are you from?" Poppy asks.')
time.sleep(3)
print('"Earth."')
time.sleep(3)
print('She blinks. "I\'ve never heard of it."')
print('...')
time.sleep(8)
print('By the time you return to the cottage, only one though fills your mind. \nHow do I get home?')
print()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
clear()
time.sleep(5)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print()
print('That evening, Oakley knocks on your door.')
print('"I\'ve been thinking about what you told me."')
print('You look up.')
print('"There may be a way to return home."')
time.sleep(3)
print('"Really?"')
print('He nods.')
time.sleep(3)
print('"Long ago, a wizard named Nox was cursed and trapped within his own shadow. \nLegend says that anyone who breaks his curse is granted one wish."')
time.sleep(5)
print('"So... if I help him..."')
time.sleep(3)
print('...')
time.sleep(3)
print('"...he may send you home."')
time.sleep(3)
print('"How?"')
print('"You must restore the magical garden. Complete eight quests, and each one will reward you with a magical plant. \nWhen the garden is full, I\'ll brew a potion strong enough to enter the Briarwood."')
time.sleep(5)
print('He smiles.')
print('"Are you ready?"')
time.sleep(3)
print('Press Enter to begin your first quest...')
print()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')